### ISSUE TITLE
element as second param

### ISSUE THREAD

**Issue by defunctzombie** [juliangruber/queryselector#1]
I would make element the second parameter so that if you leave it out then you query against the document.

**Comment by juliangruber** [comment]
What's the use of this module when you want to query the document, why not document.querySelector?

**Comment by defunctzombie** [comment]
consistency with api usage. Avoiding "globals". Also, it will minify better.

**Comment by juliangruber** [comment]
What are the globals you're talking about and why would it minify better (not that I care about minification)?

**Comment by defunctzombie** [comment]
document global and the `querySelector` call on it. It would minify better because the 'query' var would be local to the file. The bigger thing is the consistency imho. iirc there is a component that already does something similar as this.

**Comment by juliangruber** [comment]
There's [component/query](https://github.com/component/query) but that has a totally different aim.

This module is just a version of `el.querySelector` that matches `el` too.
